clear
run_lp_cs_1thetac_basicmoments
clear
run_lp_cs_3thetacs_basicmoments
clear
run_lp_cs_9thetacs_basicmoments

clear
run_lp_cs_1thetac_interactedmoments
clear
run_lp_cs_3thetacs_interactedmoments
clear
run_lp_cs_9thetacs_interactedmoments


clear
run_lp_lambda_inference_1thetac_basicmoments
clear
run_lp_lambda_inference_3thetacs_basicmoments
clear
run_lp_lambda_inference_9thetacs_basicmoments

clear
run_lp_lambda_inference_1thetac_interactedmoments
clear
run_lp_lambda_inference_3thetacs_interactedmoments
clear
run_lp_lambda_inference_9thetacs_interactedmoments